apiVersion: apps/v1
kind: Deployment
metadata:
  name: up-poc-api
  namespace: up-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: up-poc-api
  template:
    metadata:
      labels:
        app: up-poc-api
    spec:
      serviceAccountName: up-poc-api
      containers:
        - name: up-poc-api
          image: pkobylski/up-poc-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
          volumeMounts:
            - name: host-scripts
              mountPath: /host-scripts
              readOnly: true
      volumes:
        - name: host-scripts
          hostPath:
            path: /opt/update-scripts
            type: DirectoryOrCreate
