apiVersion: v1
kind: ServiceAccount
metadata:
  name: up-poc-api
  namespace: up-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: up-poc-api-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: up-poc-api-binding
subjects:
  - kind: ServiceAccount
    name: up-poc-api
    namespace: up-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: up-poc-api-role
